name: Twitter Bot

on:
  schedule:
    - cron: "0 */3 * * *"  # co 3 godziny
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DEEPINFRA_API_KEY: ${{ secrets.DEEPINFRA_API_KEY }}
          # jeśli potrzebujesz: MODEL_NAME: meta-llama/Meta-Llama-3-8B-Instruct
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        run: python3 bot.py
